### ISSUE TITLE
Updating linux-headers dependency

### ISSUE THREAD

**Issue by timparsons** [solgenomics/breedbase_dockerfile#10]
When I was trying to build the image, an error was thrown when installing `linux-headers-4.9.0-9`:

```
E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
```

Looks like this dependency should be updated to `linux-headers-4.9.0-11`

**Comment by nathanweeks** [comment]
It seems kernel headers shouldn't be necessary in the container image?
