### ISSUE TITLE
relation "cvterm" does not exist

### ISSUE THREAD

**Issue by billzt** [solgenomics/breedbase_dockerfile#25]
I followed the instructions to set a Breedbase instance using `composer`.

After opening localhost:7080, it shows a message:

Developer message:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  relation "cvterm" does not exist
LINE 1: SELECT COUNT( * ) FROM cvterm me WHERE ( name = $1 )
                               ^ [for Statement "SELECT COUNT( * ) FROM cvterm me WHERE ( name = ? )" with ParamValues: 1='breeding_program'] at lib/CXGN/BreedersToolbox/Projects.pm line 567
```

**Comment by billzt** [comment]
The main reason is that the master branch uses a blank database `breedbase/breedbase_pg12.4:v0.5`

After changing to https://github.com/solgenomics/breedbase_dockerfile/tree/topic/multiple_compose_files, it has been resolved.

**Comment by Ural-Yunusbaev** [comment]
I have the same issue. Did you install it on Linux or Windows VB?
