### ISSUE TITLE
breedbase_db    | 2023-05-17 14:26:24.380 UTC [65] FATAL:  database "breedbase" does not exist

### ISSUE THREAD

**Issue by ChenDepp** [solgenomics/breedbase_dockerfile#44]
hi @lukasmueller 
      when i running the command "docker-compose -f docker-compose.yml -f production.yml up" 
     reprot the error as below "breedbase_db    | 2023-05-17 14:26:24.380 UTC [65] FATAL:  database "breedbase" does not exist".
      
     i am deploy the web command as below:
        git clone https://github.com/solgenomics/breedbase_dockerfile
          cd breedbase_dockerfile
        touch .env
     then add 
      PGDATABASE=breedbase
        PGHOST=breedbase_db
      PGPASSWORD=postgres
       PGUSER=postgres  
     to .env 
      
     source .env 
     then when i running docker-compose -f docker-compose.yml -f production.yml up 
        it report error " database "breedbase" does not exist"."
        
   can you tell me how to solve it? thanks

**Comment by lukasmueller** [comment]
if everything else fails, connect to the docker:
docker exec -it breedbase_web bash

enter the database:
psql -h breedbase_db -U postgres

in the database, add the web_usr user and create the database:
create role web_usr with password 'postgres';
alter role web_usr with login;
create database breedbase;
\q

then, load the database with the db dump:
cat t/data/fixture/empty_fixture.sql | psql -h breedbase_db -U postgres breedbase

run the dbpatches:
cd db;
perl run_all_patches.pl -u postgres -p postgres -h breedbase_db -d breedbase -e admin -s 80

exit

Now it should work
