### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by djbutler** [solgenomics/breedbase_dockerfile#45]
Does the docker image currently support HTTPS?

**Comment by lukasmueller** [comment]
The way it works it that you run the docker without https. You configure a front end proxy, based on nginx, that does the secure layer for you. For that purpose, I recommend the Let's Encrypt system. Let me know if you need more info. I have sample configs available.

cheers
Lukas

________________________________
From: Dan Butler ***@***.***>
Sent: Tuesday, May 30, 2023 2:30 PM
To: solgenomics/breedbase_dockerfile ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [solgenomics/breedbase_dockerfile] Support for HTTPS (Issue #45)


Does the docker image currently support HTTPS?

**Comment by djbutler** [comment]
Thanks Lukas, it was pretty simple with Let's Encrypt, thanks for the reference.
