### ISSUE TITLE
Sending email confirmation to admin instead of user

### ISSUE THREAD

**Issue by djbutler** [solgenomics/breedbase_dockerfile#47]
I'm trying to send email confirmation to the admin instead of (or in addition to) the user.

I'm doing this by creating a modified version of `sgn_local.conf` with the following changes:

```
user_registration_admin_confirmation  1
user_registration_admin_confirmation_email name@example.com
```

Finally, I add this line to the `breedbase` service in `docker-compose.yml`: `./sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf`

It seems like this should enable admin email confirmation, but it doesn't appear to work. Am I missing something?

**Comment by djbutler** [comment]
I already have a 25:25 clause in my docker compose config file (https://github.com/solgenomics/breedbase_dockerfile/blob/master/docker-compose.yml).

Sorry, I should have been more specific - the confirmation emails **are** sent out successfullu, but they are sent directly to the user-provided email address. I want a way to send confirmation emails to the admins, so that they can confirm that a particular user has permission to create an account. Does that make sense?

An alternative solution would be to filter based on email domain name - but it wasn't obvious to me whether that had been implemented.

**Comment by lukasmueller** [comment]
The current version is v0.75.

Please update and run the patches, in the db/ folder, run_all_patches.pl

thanks and cheers
Lukas

________________________________

**Comment by djbutler** [comment]
Thanks I'll give that a try. It looks like `docker-compose.yml` in this repository is a bit out of date, could be worth updating.

**Comment by lukasmueller** [comment]
Thanks for the pointer. I updated it to the latest version.


________________________________

**Comment by djbutler** [comment]
Yep, newer version worked perfectly, thanks very much.
