### ISSUE TITLE
admin and password dont work

### ISSUE THREAD

**Issue by jeekinlau** [solgenomics/breedbase_dockerfile#49]
For both breedbase_docckerfile and breedbase_site repos, when i set up the docker container and try to log into the localhost::8080 it says that that the user name and password admin and password are incorrect. Maybe I am missing a crucial step? 

thanks in advanced

**Comment by lukasmueller** [comment]
Use the new breedbase_site repo, there the username and password is admin and password.

**Comment by lukasmueller** [comment]
But please change the password immediately!
