### ISSUE TITLE
admin and password do not work

### ISSUE THREAD

**Issue by avzamal** [solgenomics/breedbase_dockerfile#50]
Hello!

I have the same issue with admin login as in previous issue. When I set up the docker container and try to log into the localhost::8080 it says that that the user name and password admin and password are incorrect.  

What are the correct credentials?

Thank you in advance!

**Comment by avzamal** [comment]
Dear Lukas, thank you for your suggestion!

I tried it, but it doesn't helped

I checked the structure of the table and  sgn_people.sp_person do not have user 'admin'
![Screenshot 2024-05-15 at 11 26 23](https://github.com/solgenomics/breedbase_dockerfile/assets/70773075/162dd65e-976d-45ec-afa7-e127f75b874c)

**Comment by lukasmueller** [comment]
it loaded the test database instead of the empty database. I will check and see why

**Comment by lukasmueller** [comment]
From which repository did you download the code?

**Comment by avzamal** [comment]
I followed this repo and used "Using docker compose" part for installation as described. The only difference is the change in sgn_local.conf: instead of "dbuser web_usr" I wrote "dbuser postgres" and mounted this file to docker container in docker-compose volume section 
"- type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf "
It solved the issue with database connection as it raised an error without it

**Comment by lukasmueller** [comment]
You loaded the test database. It is probably better to rename it to something like breedbase_old and install an empty database from an empty database dump.

**Comment by lukasmueller** [comment]
That is, unless you would like to develop code, then the test database is the better option.
