### ISSUE TITLE
Incorrect file permissions on the /home/production/archive/breedbase directory

### ISSUE THREAD

**Issue by nickpalladino** [solgenomics/breedbase_dockerfile#7]
When sending a PUT request to the brapi /studies/id/observations endpoint, there following error is generated:
```
Caught exception in SGN::Controller::AJAX::BrAPI->studies_observations_granular "Can't open file /home/production/archive/breedbase/645/brapi_observations_upload/2019-09-18_20:40:09_observations.csv at lib/CXGN/UploadFile.pm line 140, <$fh> line 13."
```
This is due to incorrect file permissions on the /home/production/archive/breedbase directory in the docker image.

**Comment by nahuel-soldevilla** [comment]
I've been having a permission issue recently, kind of similar to this one:
```
[error] Caught exception in SGN::View::Mason->process "mkdir /tmp/root/SGN-site/mason: Permission denied at /home/production/cxgn/local-lib/lib/perl5/HTML/Mason/Compiler/ToObject.pm line 112.
 at /home/production/cxgn/local-lib/lib/perl5/Catalyst/View/HTML/Mason.pm line 173.
```
Happens immediately after I try to reach localhost:7080
And another one with the folder `/export` when I tried to upload a trial spatial layout.
As a workaround I've been running:
```
chown -R www-data /tmp/root/SGN-site
mkdir /export
chown www-data /export
```
But I need to do it every time I start the container in the case of SGN-site folder.

Perhaps I should create a separate issue. Do you have an idea what could be causing this?

cc @nickpalladino @nickmorales @lukasmueller @MFlores2021 @mcrimi

--
My setup:
- Ubuntu 16.04
- Running breedbase_dockerfile using the docker-compose option
- Sometimes also mounting the sgn folder with docker-compose using 
```
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - ./repos/sgn:/home/production/cxgn/sgn
```

**Comment by nickpalladino** [comment]
@nahuel-soldevilla I haven't run into any permission issues when just hitting the website. Does it still do that when you don't mount the sgn folder? The export directory probably just needs the appropriate permissions set in the dockerfile.

**Comment by nahuel-soldevilla** [comment]
@nickpalladino 
> Does it still do that when you don't mount the sgn folder?

Yes
